name: Build Mod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Gradle 7.6
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip -q gradle-7.6-bin.zip

      - name: Build
        run: ../gradle-7.6/bin/gradle build --no-daemon
        working-directory: fps-overlay

      - uses: actions/upload-artifact@v4
        with:
          name: mod
          path: fps-overlay/build/libs/*.jar
